Update submissions view and allow coordinators to view it
HEPData/hepdata pull request #477
Opened 2022-02-10 19:47 UTC by alisonrclarke

* Fixes #166

2022-03-04 21:09 UTC, GraemeWatt requested changes
This looks good.  Probably we need to deploy on QA to test properly with realistic data.  I'm not sure that clicking multiple times on the various bars (e.g. in "Submission Participants") is filtering properly.  Is it possible for the "Download Submissions CSV" file to match what's currently selected in the interactive visualisation and in the "Detailed Submission Information"?

2022-03-04 21:09 UTC, GraemeWatt commented on hepdata/ext/elasticsearch/admin_view/api.py
> +            coordinator_request = CoordinatorRequest.query.filter_by(user=submission.coordinator).first()
Maybe require `approved=True` in the filter in case the same user has other rejected Coordinator requests.

2022-03-09 10:58 UTC, alisonrclarke commented
> I'm not sure that clicking multiple times on the various bars (e.g. in "Submission Participants") is filtering properly. 

I've just checked and it looks like this is an existing issue with Submission Participants on QA. I'll investigate.

> Is it possible for the "Download Submissions CSV" file to match what's currently selected in the interactive visualisation and in the "Detailed Submission Information"?

It would be possible but might be a bit clunky to implement as the visualisation filtering is all client-side, and the CSV download all server-side. Is it something that would be useful, given that anyone using a CSV would be able to filter in spreadsheet software or in code? I think currently the box is sufficiently separate from the visualisation that users wouldn't expect it to be filtered.

2022-03-09 14:29 UTC, alisonrclarke commented
> > I'm not sure that clicking multiple times on the various bars (e.g. in "Submission Participants") is filtering properly.
> 
> I've just checked and it looks like this is an existing issue with Submission Participants on QA. I'll investigate.

Actually, looking again, I think the issue is just that it's a top 20 list, and not all submissions have participants (e.g. if you're in test mode so viewing imported records), so if you select multiple and keep selecting until they are all selected, it's still just showing you a subset of records. You have to deselect them individually to reset. I'll add a "Top 20" indicator to the list. I've also simplified the code whilst looking into the issue (as the newer versions of `crossfilter` allow for arrays in properties) so I'll push that change, which will hopefully make things more robust.

2022-03-09 16:05 UTC, alisonrclarke commented
I've also added a 'Reset filters' button which I've often found myself wanting! So if the filters are slightly misbehaving (though I think they're OK now), you can at least easily get back to the start.

2022-03-30 15:04 UTC, GraemeWatt approved these changes
> > Is it possible for the "Download Submissions CSV" file to match what's currently selected in the interactive visualisation and in the "Detailed Submission Information"?
> 
> It would be possible but might be a bit clunky to implement as the visualisation filtering is all client-side, and the CSV download all server-side. Is it something that would be useful, given that anyone using a CSV would be able to filter in spreadsheet software or in code? I think currently the box is sufficiently separate from the visualisation that users wouldn't expect it to be filtered.

OK, let's leave it for now.  We can see if any users make a request for a filtered CSV file and treat it as a separate issue if so.  I'll merge now.

2022-03-30 15:04 UTC, merged