Use OpenDistro version of elasticsearch
HEPData/hepdata pull request #478
Opened 2022-02-15 11:56 UTC by alisonrclarke

2022-02-18 21:00 UTC, GraemeWatt requested changes
Looks good, thanks.  Can we run the CI on both Elasticsearch versions similar to the multiple PostgreSQL versions?  Until the `prod` cluster is also moved to Open Distro, we'll want to keep testing the code with Elasticsearch v7.1.1.

Can the [installation instructions for Elasticsearch](https://hepdata.readthedocs.io/en/latest/installation.html#id3) be modified to explain how to install Open Distro locally (not using Docker Compose), again keeping the Elasticsearch v7.1.1 instructions?  I guess Elasticsearch v7.10.2 could be installed from Homebrew, or the [Docker image from OpenDistro](https://opendistro.github.io/for-elasticsearch-docs/docs/install/docker/) could be run instead.  I got the latter to work on my laptop (adding an option `-e "opendistro_security.disabled=true"` to the `docker run` command), but when I ran `hepdata utils reindex` I got some errors like:
```
[2022-02-18 20:14:43,334: ERROR/ForkPoolWorker-3] Task hepdata.ext.elasticsearch.api.reindex_batch[e3ed776b-e23c-42bc-ad9d-fdbdb74ff721] raised unexpected: RequestError(400, 'search_phase_execution_exception', {'error': {'root_cause': [{'type': 'query_shard_exception', 'reason': '[has_parent] no join field has been configured', 'index_uuid': 'hwlsypzZTiu4ELfjXXFQMw', 'index': 'hepdata-main'}], 'type': 'search_phase_execution_exception', 'reason': 'all shards failed', 'phase': 'query', 'grouped': True, 'failed_shards': [{'shard': 0, 'index': 'hepdata-main', 'node': 'V1gOSA4IShao5hyLYOZLGw', 'reason': {'type': 'query_shard_exception', 'reason': '[has_parent] no join field has been configured', 'index_uuid': 'hwlsypzZTiu4ELfjXXFQMw', 'index': 'hepdata-main'}}]}, 'status': 400})
```
Can you please check if you get this error and see if any changes are needed when upgrading from Elasticsearch v7.1.1 to v7.10.2?  I checked that upgrading to the Python packages `elasticsearch==7.17.0` and `elasticsearch-dsl==7.4.0` gives an exception with Open Distro (`elasticsearch.exceptions.UnsupportedProductError: The client noticed that the server is not a supported distribution of Elasticsearch`) so we'll need to stick with the older versions.

2022-02-24 10:28 UTC, alisonrclarke commented
> ... when I ran `hepdata utils reindex` I got some errors like:
> 
> ```
> [2022-02-18 20:14:43,334: ERROR/ForkPoolWorker-3] Task hepdata.ext.elasticsearch.api.reindex_batch[e3ed776b-e23c-42bc-ad9d-fdbdb74ff721] raised unexpected: RequestError(400, 'search_phase_execution_exception', {'error': {'root_cause': [{'type': 'query_shard_exception', 'reason': '[has_parent] no join field has been configured', 'index_uuid': 'hwlsypzZTiu4ELfjXXFQMw', 'index': 'hepdata-main'}], 'type': 'search_phase_execution_exception', 'reason': 'all shards failed', 'phase': 'query', 'grouped': True, 'failed_shards': [{'shard': 0, 'index': 'hepdata-main', 'node': 'V1gOSA4IShao5hyLYOZLGw', 'reason': {'type': 'query_shard_exception', 'reason': '[has_parent] no join field has been configured', 'index_uuid': 'hwlsypzZTiu4ELfjXXFQMw', 'index': 'hepdata-main'}}]}, 'status': 400})
> ```

I think we will need to recreate the index when updating versions: `hepdata utils reindex --recreate=true` worked OK for me when switching from v7.1 to v7.10.

2022-02-24 10:33 UTC, alisonrclarke commented
I think I've now got the matrix working. I took out the Postgres 9.6 now we've upgraded the production DB, so that we weren't increasing the number of runs too much. We will need to change the required checks settings when we're ready to merge.

I've also updated the installation instructions.

2022-02-25 12:06 UTC, GraemeWatt approved these changes

2022-02-25 12:07 UTC, merged