Installation Updates
HEPData/hepdata pull request #501
Opened 2022-04-25 15:13 UTC by zeynepaki

Updates for easier installation

2022-04-25 16:14 UTC, GraemeWatt requested changes
Thanks for your first contribution, @zeynepaki!  I've not personally had issues with `.DS_Store` or `pluggy`, but I'm happy to make these changes if you had problems.

The CI tests are currently failing because the docs are built with `-W` which turns warnings into errors.  A blank line is needed before the list of services.  If you're making changes to the docs, please check you can build locally before pushing to GitHub:

```bash
cd docs
make html SPHINXOPTS="-W"
open _build/html/index.html
```
This would be a good thing to mention in the developer docs.  Can you please add a new section on "Building the docs" maybe after "Running the tests" in `INSTALL.rst`?

2022-04-25 16:14 UTC, GraemeWatt commented on INSTALL.rst
> +for example, using ``yum`` or ``apt-get`` for Linux or ``brew`` for macOS:
Need to insert a blank line here to avoid an error message: `../INSTALL.rst:35: ERROR: Unexpected indentation.`

2022-04-27 15:48 UTC, zeynepaki commented on INSTALL.rst
> +for example, using ``yum`` or ``apt-get`` for Linux or ``brew`` for macOS:
Hi Graeme! Thank you for the warm welcome! This should be done now.

2022-04-27 15:53 UTC, GraemeWatt approved these changes

2022-04-27 15:54 UTC, merged